### ISSUE TITLE
psycopg2.errors.UndefinedTable: relation "k_reports" does not exist

### ISSUE THREAD

**Issue by hugodopradofernandes** [klustair/klustair#17]
This issue returned on v0.3.0
Installed from scratch (deleted previous version, deleted namespace and installed again)

```
klustair-runnerjob
DEBUG:run Trivy on: quay.io/prometheus/prometheus:v2.21.0
klustair-runnerjob
DEBUG:run Trivy on: quay.io/prometheus/alertmanager:v0.21.0
klustair-runnerjob
DEBUG:run Trivy on: rancher/nginx-ingress-controller:nginx-0.35.0-rancher2
klustair-runnerjob
DEBUG:run Trivy on: klustair/klustair:v0.3.0
klustair-runnerjob
DEBUG:run Trivy on: weaveworks/scope:1.13.1
klustair-runnerjob
DEBUG:run Trivy on: klustair/klustair-frontend:v0.3.0-php-fpm
klustair-runnerjob
DEBUG:run Trivy on: quay.io/coreos/kube-state-metrics:v1.9.7
klustair-runnerjob
DEBUG:run Trivy on: squareup/ghostunnel:v1.5.2
klustair-runnerjob
DEBUG:run Trivy on: klustair/klustair-frontend:v0.3.0-apache
klustair-runnerjob
DEBUG:run Trivy on: docker.io/bitnami/wordpress:5.5.1-debian-10-r49
klustair-runnerjob
DEBUG:run Trivy on: kiwigrid/k8s-sidecar:0.1.209
klustair-runnerjob
INFO: Load Namespaces
klustair-runnerjob
INFO: Run Kubeaudit
klustair-runnerjob
not categorized: NamespaceHostNetworkTrue
klustair-runnerjob
not categorized: SeccompAnnotationMissing
klustair-runnerjob
not categorized: AutomountServiceAccountTokenTrueAndDefaultSA
klustair-runnerjob
not categorized: SeccompAnnotationMissing
klustair-runnerjob
not categorized: NamespaceHostNetworkTrue
klustair-runnerjob
not categorized: NamespaceHostPIDTrue
klustair-runnerjob
not categorized: SeccompAnnotationMissing
klustair-runnerjob
not categorized: SeccompAnnotationMissing
klustair-runnerjob
not categorized: AutomountServiceAccountTokenTrueAndDefaultSA
klustair-runnerjob
not categorized: NamespaceHostNetworkTrue
klustair-runnerjob
not categorized: NamespaceHostPIDTrue
klustair-runnerjob
not categorized: SeccompAnnotationMissing
klustair-runnerjob
INFO: Load Pod an Container informations
klustair-runnerjob
INFO: Start Trivy analysis
klustair-runnerjob
INFO: Load trivy Vulnerabilities
klustair-runnerjob
ERROR: could not parse quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
klustair-runnerjob
INFO: Save data to DB
klustair-runnerjob
INFO: Got a DB Connection.
klustair-runnerjob
Traceback (most recent call last):
klustair-runnerjob
File "./app/runner.py", line 343, in <module>
klustair-runnerjob
run()
klustair-runnerjob
File "./app/runner.py", line 285, in run
klustair-runnerjob
db.saveReport(report)
klustair-runnerjob
File "/app/database.py", line 71, in saveReport
klustair-runnerjob
self.__cursor.execute('''INSERT INTO k_reports(
klustair-runnerjob
psycopg2.errors.UndefinedTable: relation "k_reports" does not exist
klustair-runnerjob
LINE 1: INSERT INTO k_reports(
klustair-runnerjob
^
```

**Comment by mms-gianni** [comment]
k_reports is the first insert statement. 

This may happen, when the klustair init container starts earlier than the PostgreSQL. No migrations are able to run then. So no Database is created. 

```
kubectl logs klustair030-frontend-979 -c klustair-init
======= Prepare Storage:
created directory: 'storage/app/'
created directory: 'storage/app/public'
created directory: 'storage/debugbar'
created directory: 'storage/framework/'
created directory: 'storage/framework/cache'
created directory: 'storage/framework/sessions'
created directory: 'storage/framework/testing'
created directory: 'storage/framework/views'
created directory: 'storage/logs/'
======= Database Migrations
[2021-01-06 20:54:27] local.ERROR: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "klustair030-postgresql" (10.8.10.29) and accepting
	TCP/IP connections on port 5432? (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused
\tIs the server running on host \"klustair030-postgresql\" (10.8.10.29) and accepting
\tTCP/IP connections on port 5432? (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations and table_type = 'BASE TABLE') at /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)
[stacktrace]
#0 /var/www/vendo
```

Loging in a to the running frontend container and reexecute the init.sh script fixes the problem in the short therm. 
```
kubectl exec -it klustair030-frontend-979 -- bash -l
root@klustair030-frontend-979:/var/www# sh init.sh
```

But i will definitly add a check to the init script to wait until the PostgreSQL database is ready.

**Comment by mms-gianni** [comment]
This should fix it permanently : 
https://github.com/klustair/klustair-frontend/pull/54
