### ISSUE TITLE
v0.4.0 Cant save the report due to missing timedelta

### ISSUE THREAD

**Issue by mms-gianni** [klustair/klustair#24]
DEBUG:http://klustair-frontend:80 "POST /api/v1/pac/report/16eecc80-bb87-464b-8b2b-f305b62fecd2/summary/create HTTP/1.1" 200 328
Traceback (most recent call last):
  File "/app/./runner.py", line 370, in <module>
    run()
  File "/app/./runner.py", line 300, in run
    api.cleanupDB(args.limitDate, args.limitNr)
  File "/app/api.py", line 81, in cleanupDB
    d = timedelta(days = int(limitDate))
ValueError: invalid literal for int() with base 10: 'false'

**Comment by mms-gianni** [comment]
Workaround: add aLIMITDATE (-ld) parameter.

**Comment by mms-gianni** [comment]
This should be fixed now. v0.4.0 was rebuilt and published. 

https://github.com/klustair/klustair/commit/9405846e571fd90d0feae7957e9a9b6c843edd68
